#!/bin/bash
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
### BEGIN INIT INFO
# Provides:          start-jupyter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Jupyter Notebook's service
# Description:       Executes jupyter notebook in background.
### END INIT INFO   Startup script for Linux-based systems for Executes jupyter notebook in background
case $1 in
    start)
        echo "Starting script jupyter-notebook "
        /home/jupyter-nodebook/env/bin/jupyter-notebook notebook --no-browser --notebook-dir='/home/jupyter-nodebook/' --config='~/.jupyter/jupyter_notebook_config.py' >
    ;;
    stop)
        echo "Stopping script jupyter-notebook "
        /home/jupyter-nodebook/env/bin/jupyter-notebook stop
    ;;
    restart)
        echo "Restarting jupyter-notebook "
        /home/jupyter-nodebook/env/bin/jupyter-notebook stop
        /home/jupyter-nodebook/env/bin/jupyter-notebook --no-browser --notebook-dir='/home/jupyter-nodebook/'  --config='~/.jupyter/jupyter_notebook_config.py'
    ;;
    *)
        echo "jupyter-notebook {start|stop|restart}"
        exit 1
    ;;
esac
exit 0
