#!/bin/bash

### BEGIN INIT INFO
# Provides:          start-jupyter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Jupyter Notebook's service
# Description:       Executes jupyter notebook in background.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="Start Jupyter notebook server as a service"
DAEMON=/usr/local/bin/jupyter-notebook
DAEMON_ARGS="--no-browser --notebook-dir='~/jupyter-nodebook/' --config=~/.jupyter/jupyter_notebook_config.py"

case $1 in
    start)
        echo "Starting script jupyter-notebook "
        $DAEMON $DAEMON_ARGS
    ;;
    stop)
        echo "Stopping script jupyter-notebook "
        $DAEMON stop
    ;;
    restart)
        echo "Restarting jupyter-notebook "
        $DAEMON stop
        $DAEMON $DAEMON_ARGS
    ;;
    *)
        echo "jupyter-notebook {start|stop|restart}"
        exit 1
    ;;
esac
exit 0
